version: '3'

vars:
  BINARY_NAME: medspa-api
  BUILD_DIR: ./bin
  MAIN_PATH: ./cmd/api

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list

  build:
    desc: Build the API server
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -o {{.BUILD_DIR}}/{{.BINARY_NAME}} {{.MAIN_PATH}}
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - "{{.BUILD_DIR}}/{{.BINARY_NAME}}"

  run:
    desc: Run the API server locally
    deps: [build]
    cmds:
      - "{{.BUILD_DIR}}/{{.BINARY_NAME}}"

  test:
    desc: Run all tests
    cmds:
      - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

  test-coverage:
    desc: Run tests and show coverage report
    cmds:
      - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - go tool cover -html=coverage.txt -o coverage.html
      - echo "Coverage report generated at coverage.html"

  lint:
    desc: Run linters
    cmds:
      - gofmt -l -w .
      - go vet ./...
      - go mod tidy

  fmt:
    desc: Format code
    cmds:
      - gofmt -l -w .

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -f coverage.txt coverage.html

  deps:
    desc: Download dependencies
    cmds:
      - go mod download
      - go mod verify

  tf-fmt:
    desc: Format Terraform files
    dir: infra/terraform
    cmds:
      - terraform fmt -recursive

  tf-validate:
    desc: Validate Terraform configuration
    dir: infra/terraform
    cmds:
      - terraform init -backend=false
      - terraform validate

  tf-plan:
    desc: Run Terraform plan
    dir: infra/terraform
    cmds:
      - terraform plan

  tf-apply:
    desc: Apply Terraform changes
    dir: infra/terraform
    cmds:
      - terraform apply

  docker-up:
    desc: Start local stack (API + Postgres + Redis + LocalStack)
    cmds:
      - docker compose up --build

  docker-down:
    desc: Stop local stack and remove containers
    cmds:
      - docker compose down -v

  ci:
    desc: Run all CI checks
    cmds:
      - task: fmt
      - task: lint
      - task: test
      - task: tf-fmt
      - task: tf-validate
