// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package paymentsql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Booking struct {
	ID           pgtype.UUID
	OrgID        string
	LeadID       pgtype.UUID
	Status       string
	ConfirmedAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	ScheduledFor pgtype.Timestamptz
}

type Lead struct {
	ID        pgtype.UUID
	OrgID     string
	Name      pgtype.Text
	Email     pgtype.Text
	Phone     pgtype.Text
	Message   pgtype.Text
	Source    pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type Outbox struct {
	ID          pgtype.UUID
	OrgID       pgtype.Text
	Type        string
	Payload     []byte
	CreatedAt   pgtype.Timestamptz
	DeliveredAt pgtype.Timestamptz
}

type Payment struct {
	ID              pgtype.UUID
	OrgID           string
	LeadID          pgtype.UUID
	Provider        string
	ProviderRef     pgtype.Text
	BookingIntentID pgtype.UUID
	AmountCents     int32
	Status          string
	CreatedAt       pgtype.Timestamptz
}

type ProcessedEvent struct {
	Provider    string
	EventID     string
	ProcessedAt pgtype.Timestamptz
}
