// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package paymentsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetOpenDepositByOrgAndLead(ctx context.Context, arg GetOpenDepositByOrgAndLeadParams) (Payment, error)
	GetPaymentByID(ctx context.Context, id pgtype.UUID) (Payment, error)
	GetPaymentByProviderRef(ctx context.Context, providerRef pgtype.Text) (Payment, error)
	InsertPayment(ctx context.Context, arg InsertPaymentParams) (Payment, error)
	UpdatePaymentStatusByID(ctx context.Context, arg UpdatePaymentStatusByIDParams) (Payment, error)
	UpdatePaymentStatusByProviderRef(ctx context.Context, arg UpdatePaymentStatusByProviderRefParams) (Payment, error)
}

var _ Querier = (*Queries)(nil)
