// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package paymentsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, org_id, lead_id, provider, provider_ref, booking_intent_id, amount_cents, status, scheduled_for, created_at FROM payments
WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.LeadID,
		&i.Provider,
		&i.ProviderRef,
		&i.BookingIntentID,
		&i.AmountCents,
		&i.Status,
		&i.ScheduledFor,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByProviderRef = `-- name: GetPaymentByProviderRef :one
SELECT id, org_id, lead_id, provider, provider_ref, booking_intent_id, amount_cents, status, scheduled_for, created_at FROM payments
WHERE provider_ref = $1
`

func (q *Queries) GetPaymentByProviderRef(ctx context.Context, providerRef pgtype.Text) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByProviderRef, providerRef)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.LeadID,
		&i.Provider,
		&i.ProviderRef,
		&i.BookingIntentID,
		&i.AmountCents,
		&i.Status,
		&i.ScheduledFor,
		&i.CreatedAt,
	)
	return i, err
}

const insertPayment = `-- name: InsertPayment :one
INSERT INTO payments (
    id,
    org_id,
    lead_id,
    provider,
    provider_ref,
    booking_intent_id,
    amount_cents,
    status,
    scheduled_for
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, org_id, lead_id, provider, provider_ref, booking_intent_id, amount_cents, status, scheduled_for, created_at
`

type InsertPaymentParams struct {
	ID              pgtype.UUID
	OrgID           string
	LeadID          pgtype.UUID
	Provider        string
	ProviderRef     pgtype.Text
	BookingIntentID pgtype.UUID
	AmountCents     int32
	Status          string
	ScheduledFor    pgtype.Timestamptz
}

func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, insertPayment,
		arg.ID,
		arg.OrgID,
		arg.LeadID,
		arg.Provider,
		arg.ProviderRef,
		arg.BookingIntentID,
		arg.AmountCents,
		arg.Status,
		arg.ScheduledFor,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.LeadID,
		&i.Provider,
		&i.ProviderRef,
		&i.BookingIntentID,
		&i.AmountCents,
		&i.Status,
		&i.ScheduledFor,
		&i.CreatedAt,
	)
	return i, err
}

const updatePaymentStatusByID = `-- name: UpdatePaymentStatusByID :one
UPDATE payments
SET status = $2,
    provider_ref = COALESCE($3, provider_ref)
WHERE id = $1
RETURNING id, org_id, lead_id, provider, provider_ref, booking_intent_id, amount_cents, status, scheduled_for, created_at
`

type UpdatePaymentStatusByIDParams struct {
	ID          pgtype.UUID
	Status      string
	ProviderRef pgtype.Text
}

func (q *Queries) UpdatePaymentStatusByID(ctx context.Context, arg UpdatePaymentStatusByIDParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatusByID, arg.ID, arg.Status, arg.ProviderRef)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.LeadID,
		&i.Provider,
		&i.ProviderRef,
		&i.BookingIntentID,
		&i.AmountCents,
		&i.Status,
		&i.ScheduledFor,
		&i.CreatedAt,
	)
	return i, err
}

const updatePaymentStatusByProviderRef = `-- name: UpdatePaymentStatusByProviderRef :one
UPDATE payments
SET status = $2,
    provider_ref = COALESCE($3, provider_ref)
WHERE provider_ref = $1
RETURNING id, org_id, lead_id, provider, provider_ref, booking_intent_id, amount_cents, status, scheduled_for, created_at
`

type UpdatePaymentStatusByProviderRefParams struct {
	ProviderRef   pgtype.Text
	Status        string
	ProviderRef_2 pgtype.Text
}

func (q *Queries) UpdatePaymentStatusByProviderRef(ctx context.Context, arg UpdatePaymentStatusByProviderRefParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatusByProviderRef, arg.ProviderRef, arg.Status, arg.ProviderRef_2)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.LeadID,
		&i.Provider,
		&i.ProviderRef,
		&i.BookingIntentID,
		&i.AmountCents,
		&i.Status,
		&i.ScheduledFor,
		&i.CreatedAt,
	)
	return i, err
}
