// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package bookingsql

import (
	"context"
)

type Querier interface {
	GetBookingForOrg(ctx context.Context, arg GetBookingForOrgParams) (Booking, error)
	InsertBooking(ctx context.Context, arg InsertBookingParams) (Booking, error)
}

var _ Querier = (*Queries)(nil)
