// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package bookingsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBookingForOrg = `-- name: GetBookingForOrg :one
SELECT id, org_id, lead_id, status, confirmed_at, created_at, scheduled_for FROM bookings
WHERE id = $1
  AND org_id = $2
`

type GetBookingForOrgParams struct {
	ID    pgtype.UUID
	OrgID string
}

func (q *Queries) GetBookingForOrg(ctx context.Context, arg GetBookingForOrgParams) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingForOrg, arg.ID, arg.OrgID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.LeadID,
		&i.Status,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.ScheduledFor,
	)
	return i, err
}

const insertBooking = `-- name: InsertBooking :one
INSERT INTO bookings (
    id,
    org_id,
    lead_id,
    status,
    confirmed_at,
    scheduled_for
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, lead_id, status, confirmed_at, created_at, scheduled_for
`

type InsertBookingParams struct {
	ID           pgtype.UUID
	OrgID        string
	LeadID       pgtype.UUID
	Status       string
	ConfirmedAt  pgtype.Timestamptz
	ScheduledFor pgtype.Timestamptz
}

func (q *Queries) InsertBooking(ctx context.Context, arg InsertBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, insertBooking,
		arg.ID,
		arg.OrgID,
		arg.LeadID,
		arg.Status,
		arg.ConfirmedAt,
		arg.ScheduledFor,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.LeadID,
		&i.Status,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.ScheduledFor,
	)
	return i, err
}
